# Generated by Django 4.2.7 on 2023-11-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_city_country_alter_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('password1', models.CharField(blank=True, max_length=255, null=True)),
                ('password2', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(default='qwert@gmai.com', max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
