# Generated by Django 4.2.7 on 2023-11-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('email', models.EmailField(default='qwert@gmai.com', max_length=254, null=True)),
                ('choice_evaluations', models.IntegerField(choices=[(1, 'Дуже погано'), (2, 'Погано'), (3, 'Задовільно'), (4, 'Добре'), (5, 'Відміно')], default=0)),
                ('reaction', models.IntegerField(choices=[(1, 'Негативний відгук'), (2, 'Позитивний відгук')], default=0)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('products', models.ManyToManyField(to='main.product')),
            ],
        ),
    ]
