# Generated by Django 4.2.7 on 2023-11-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='phone',
            field=models.CharField(default=380),
        ),
    ]
