# Generated by Django 4.2.7 on 2023-11-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_response_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='phone',
            field=models.CharField(default=380, max_length=17),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=380, max_length=17),
        ),
    ]
